[platform]
display_name = Mastodon
name = mastodon
; proto_id: 0 = OAuth2, 1 = PNBA
proto_id = 0
; cat_id: 0 = Email, 1 = Message, 2 = Text, 3 = Bridge
cat_id = 2
; true or false
supports_offline_first = false
icon_svg = https://raw.githubusercontent.com/smswithoutborders/mastodon-oauth2-adapter/main/icons/mastodon.svg
icon_png = https://raw.githubusercontent.com/smswithoutborders/mastodon-oauth2-adapter/main/icons/mastodon.png

[author]
name = Aisatou Musa
email = sashaaysha77@gmail.com
